---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: iris-blue-apps
  namespace: iris-blue
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/iris-blue-apps

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iris-blue-apps
  namespace: iris-blue
spec:
  interval: 5m
  serviceAccountName: tenant-flux-reconciler
  targetNamespace: iris-blue-apps
  chart:
    spec:
      chart: iris-blue-apps/
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: iris-blue-apps
        namespace: iris-blue
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    httpproxy:
      fqdn: iris-blue-app.dev.fluxtmc.aws.warroyo.com
    apptext: iris-blue dev app